{
 "title": "Workshop",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services up",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by(mode) (rate(node_cpu_seconds_total{mode=~\"(user|system)\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"demo\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "RabbitMQ Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_acked_total",
     "legendFormat": "total messges"
    },
    {
     "expr": "rabbitmq_queue_messages_unacked",
     "legendFormat": "unacked messages"
    }
   ]
  },
  {
   "title": "RabbitMQ Consumers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    { "expr": "rabbitmq_consumers", "legendFormat": "consumers" }
   ]
  },
  {
   "title": "RabbitMQ Ack rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_delivered_ack_total{job=\"rabbitmq\"}[1m])",
     "legendFormat": "rate"
    }
   ]
  },
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{method}}: {{endpoint}}" }
   ]
  },
  {
   "title": "Fruits recieved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "recent_fruits", "legendFormat": "{{fruit}}" }
   ]
  },
  {
   "title": "Sent MQ messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(mq_publish_total{job=\"frontend\"}[1m]) * 60",
     "legendFormat": "Sent to {{queue}}"
    }
   ]
  },
  {
   "title": "p95/p75/p50 percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mq_publish_latency_bucket{job=\"frontend\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(mq_publish_latency_bucket{job=\"frontend\"}[1m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(mq_publish_latency_bucket{job=\"frontend\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Busy workers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "worker_busy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Processed jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "expr": "rate(jobs_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB p95, p50 latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(database_insert_latency_bucket[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(database_insert_latency_bucket[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Cache deletions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(cache_delete_latency_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}