global:
  scrape_interval: 15s

# Note: This configuration file is using 'localhost' as we're running all the services
# using the "network_mode: host" option in the docker-compose.yml file.
# In the real world, we're using the service name as the target, most likely the container name
# or the fully qualified domain name (FQDN) of the service.
# But, as we want to be able to reach frontend/backend without any hassle, we're using localhost.

# If you change this file, you can kill -HUP the Prometheus process to reload the configuration.
# eg:
# docker exec -ti prometheus kill -HUP 1

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['localhost:15692']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['localhost:9187']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['localhost:9121']

  - job_name: 'frontend'
    static_configs:
      - targets: ['localhost:5000']

  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:5001']