services:
  postgres:
    network_mode: host
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    network_mode: host
    image: rabbitmq:4.0.4
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  prometheus:
    network_mode: host
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./contrib/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    network_mode: host
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  node_exporter:
    network_mode: host
    image: prom/node-exporter:latest
    container_name: node_exporter

  postgres_exporter:
    network_mode: host
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://demo:demo@localhost:5432/demo?sslmode=disable"

  valkey:
    network_mode: host
    image: valkey/valkey:latest
    container_name: valkey
    volumes:
      - valkey_data:/data

  redis_exporter:
    network_mode: host
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    environment:
      REDIS_ADDR: "localhost:6379"

  blackbox_exporter:
    network_mode: host
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    volumes:
      - ./contrib/blackbox-exporter.yml:/etc/blackbox_exporter/config.yml

volumes:
  postgres_data:
  rabbitmq_data:
  prometheus_data:
  valkey_data:
