services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - localnet

  rabbitmq:
    image: rabbitmq:4.0.4
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15692:15692"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - localnet

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./contrib/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - localnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - localnet

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - localnet

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://demo:demo@postgres:5432/demo?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - localnet


networks:
  localnet:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
